services:
  parkour2-nginx:
    container_name: parkour2-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx-daemon.conf:/etc/nginx/nginx.conf
      - ./nginx-server.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/ssl/cert.pem
      - ./key.pem:/etc/ssl/key.pem
      - parkour2_media:/parkour2/media
      - parkour2_staticfiles:/parkour2/static

volumes:
  parkour2_media:
    external: true
  parkour2_staticfiles:
    external: true

networks:
  parkour2_default:
    external: true