services:
  parkour2-rsnapshot:
    container_name: parkour2-rsnapshot
    image: lscr.io/linuxserver/rsnapshot:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./rsnapshot/config:/config
      - ./rsnapshot/backups:/.snapshots
      # sources go into /data
      - parkour2_pgdb:/data/parkour2_pgdb
      - parkour2_media:/data/parkour2_media

volumes:
  parkour2_pgdb:
    external: true
  parkour2_media:
    external: true

networks:
  parkour2_default:
    external: true
