ci:
  autofix_commit_msg: |
    [pre-commit] fixes from hooks
  autofix_prs: true
  autoupdate_branch: "develop"
  autoupdate_commit_msg: "pre-commit.ci autoupdate"
  autoupdate_schedule: monthly
  skip: []
  submodules: false

repos:
  - repo: local
    hooks:
      - id: set-base-docker
        name: set-base-docker
        entry: /usr/bin/make
        language: script
        pass_filenames: false
        files: docker-compose\.yml
        args: ["set-base"]
      - id: hardreset-caddyfile
        name: hardreset-caddyfile
        entry: /usr/bin/make
        language: script
        pass_filenames: false
        files: misc/Caddyfile
        args: ["hardreset-caddyfile"]
      - id: hardreset-envfile
        name: hardreset-envfile
        entry: /usr/bin/make
        language: script
        pass_filenames: false
        files: misc/parkour.env
        args: ["hardreset-envfile"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      - id: check-merge-conflict
        types: [python]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff-format
        args: [--target-version, py312] # 3.12
  # - repo: https://github.com/dosisod/refurb
  #   rev: v2.0.0
  #   hooks:
  #     - id: refurb
  #       args: [--python-version, "3.12", --sort, error]  #, --format, gitub
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py312-plus] # 3.12
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.22.2
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        args: [--trailing-comma, none, --no-error-on-unmatched-pattern]
        types_or: [json, css, javascript, vue]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [--skip, "backend/static/*,backend/**/tests.py,backend/**/fixtures/*.json,misc/demo-dump.json", --write-changes]
