# Generated by Django 4.2.16 on 2024-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "library_sample_shared",
            "0011_alter_indexi5_number_alter_indexi5_prefix_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organism",
            name="alias_label",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                verbose_name="For data directories",
            ),
        ),
        migrations.AddField(
            model_name="organism",
            name="snakepipes_yaml",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="SnakePipes YAML"
            ),
        ),
    ]
