# Generated by Django 4.2.9 on 2025-01-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_alter_sample_concentration_method'),
        ('index_generator', '0011_alter_poolsize_short_name'),
        ('library', '0007_alter_library_concentration_method'),
        ('pooling', '0004_archived_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooling',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index_generator.pool', verbose_name='pool'),
        ),
        migrations.AlterField(
            model_name='pooling',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.library', verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='pooling',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.sample', verbose_name='Sample'),
        ),
    ]
