# Generated by Django 4.2.16 on 2024-11-04 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import request.models
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0013_historicalprincipalinvestigator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("request", "0008_alter_request_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Create Time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Update Time"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(default="Empty", verbose_name="Description"),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "deep_seq_request",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Deep Sequencing Request",
                    ),
                ),
                (
                    "samples_submitted",
                    models.BooleanField(
                        default=False, verbose_name="Samples Submitted"
                    ),
                ),
                (
                    "sequenced",
                    models.BooleanField(default=False, verbose_name="Sequenced"),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                (
                    "filepaths",
                    models.JSONField(default=request.models.filepaths_default),
                ),
                (
                    "metapaths",
                    models.JSONField(default=request.models.metapaths_default),
                ),
                ("approval", models.JSONField(default=request.models.approval_default)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cost_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="common.costunit",
                        verbose_name="Cost Unit",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical request",
                "verbose_name_plural": "historical requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
