# Generated by Django 4.2.19 on 2025-02-06 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import request.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0018_historicalorganization_historicalduty_and_more'),
        ('index_generator', '0011_alter_poolsize_short_name'),
        ('request', '0015_alter_request_approval_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='HistoricalRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_time', models.DateTimeField(blank=True, editable=False, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(blank=True, editable=False, verbose_name='Update Time')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='')),
                ('token', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Token')),
                ('pooled_libraries', models.BooleanField(default=False, verbose_name='Pooled libraries?')),
                ('pooled_libraries_concentration_user', models.FloatField(blank=True, null=True, verbose_name='Library pool Concentration by User')),
                ('pooled_libraries_volume_user', models.FloatField(blank=True, null=True, verbose_name='Library pool Volume by User')),
                ('pooled_libraries_fragment_size_user', models.PositiveIntegerField(blank=True, null=True, verbose_name='Library pool Mean Fragment Size by User')),
                ('deep_seq_request', models.TextField(blank=True, max_length=100, null=True, verbose_name='Deep Sequencing Request')),
                ('approval_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Approval Time')),
                ('samples_submitted', models.BooleanField(default=False, verbose_name='Samples Submitted')),
                ('samples_submitted_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Samples Submitted Time')),
                ('sequenced', models.BooleanField(default=False, verbose_name='Sequenced')),
                ('invoice_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Invoice Date')),
                ('archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('filepaths', models.JSONField(default=request.models.filepaths_default)),
                ('metapaths', models.JSONField(default=request.models.metapaths_default)),
                ('approval', models.JSONField(default=request.models.approval_default)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approval_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approval user')),
                ('bioinformatician', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Bioinformatician')),
                ('cost_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='common.costunit', verbose_name='Cost Unit')),
                ('handler', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Handler')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='PI')),
                ('pool_size_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='index_generator.poolsize', verbose_name='Sequencing kit (user)')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical request',
                'verbose_name_plural': 'historical requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
