name: Frontend

on:
  workflow_dispatch:
  push:
    branches: ['develop']
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - closed


jobs:
  test-and-report:
    if: github.repository == 'maxplanck-ie/parkour2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Playwright rule
        run: |
          make playwright
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-suite-report
          # if-no-files-found: ignore  ## default: warn
          path: |
            backend/frontend_testing_suite/videos/
            backend/frontend_testing_suite/results/
          retention-days: 30
